spring.application.name=colegiointegracao
# Configuração do MongoDB (Atlas)
spring.data.mongodb.uri=mongodb+srv://myAtlasDBUser:XcNixIjtQaHi3q1g@myatlasclusteredu.8iwrr.mongodb.net/back?retryWrites=true&w=majority
spring.data.mongodb.database=back

# Logs detalhados para diagnosticar problemas
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=DEBUG

# Desabilitar auto-configuração do DataSource (já que você não está usando um banco relacional)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration